name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install uiua from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: uiua
          version: "0.13"
      - name: Run uiua tests
        run: uiua test test.ua
